const mockBusData = [
    {
        id: 1,
        tripType: "One-way",
        fromCity: "Kathmandu",
        toCity: "Pokhara",
        date: "2024-10-20",
        passengers: 2,
        busCompany: "Sajilo Yatra",
        departureTime: "07:00 AM",
        arrivalTime: "10:00 AM",
        price: 1500,
    },
    {
        id: 2,
        tripType: "One-way",
        fromCity: "Kathmandu",
        toCity: "Bhaktapur",
        date: "2024-10-21",
        passengers: 10,
        busCompany: "Greenline Travels",
        departureTime: "09:00 AM",
        arrivalTime: "10:30 AM",
        price: 500,
    },
    {
        id: 3,
        tripType: "Two-way",
        fromCity: "Pokhara",
        toCity: "Lalitpur",
        date: "2024-10-22",
        passengers: 24,
        busCompany: "Nepal Yatra",
        departureTime: "12:00 PM",
        arrivalTime: "03:00 PM",
        returnDepartureTime: "05:00 PM",
        returnArrivalTime: "08:00 PM",
        price: 2000,
    },
    {
        id: 4,
        tripType: "One-way",
        fromCity: "Biratnagar",
        toCity: "Kathmandu",
        date: "2024-10-23",
        passengers: 10,
        busCompany: "Shree Sita Travels",
        departureTime: "06:00 AM",
        arrivalTime: "10:00 AM",
        price: 1200,
    }
];